MODULE OPOV_DEMO
	TYPE ENTITY
		INTEGER(KIND = 4)	:: ENTITY_ID
		REAL(KIND = 8) 		:: ENTITY_VALUE
	END TYPE ENTITY
	
	INTERFACE ASSIGNMENT (=)
		MODULE PROCEDURE ENTITY_EQUIVALENCE
	END INTERFACE
	
	INTERFACE OPERATOR (+)
		MODULE PROCEDURE ENTITY_ADDITION
	END INTERFACE
	
	INTERFACE OPERATOR (-)
		MODULE PROCEDURE ENTITY_SUBTRACTION
	END INTERFACE
	
	
	
CONTAINS
	SUBROUTINE PRINT_ENTITY(E1)
		TYPE(ENTITY),INTENT(IN) :: E1	
		WRITE(*,*) E1%ENTITY_ID, "---", E1%ENTITY_VALUE
	END SUBROUTINE PRINT_ENTITY

	FUNCTION ENTITY_ADDITION(E1,E2) RESULT (E3)
		TYPE(ENTITY),INTENT(IN) :: E1, E2
		TYPE(ENTITY) :: E3	
		E3%ENTITY_ID	= E1%ENTITY_ID + E2%ENTITY_ID
		E3%ENTITY_VALUE = E1%ENTITY_VALUE + E2%ENTITY_VALUE
	END FUNCTION ENTITY_ADDITION
	
	FUNCTION ENTITY_SUBTRACTION(E1,E2) RESULT (E3)
	TYPE(ENTITY),INTENT(IN) :: E1, E2
		TYPE(ENTITY) :: E3	
		E3%ENTITY_ID	= E1%ENTITY_ID - E2%ENTITY_ID
		E3%ENTITY_VALUE = E1%ENTITY_VALUE - E2%ENTITY_VALUE
	END FUNCTION ENTITY_SUBTRACTION
	
	SUBROUTINE ENTITY_EQUIVALENCE(E1,E2)
		TYPE(ENTITY),INTENT(IN) :: E2	
		TYPE(ENTITY),INTENT(OUT) :: E1
		E1%ENTITY_ID	= E2%ENTITY_ID
		E1%ENTITY_VALUE = E2%ENTITY_VALUE
	END SUBROUTINE ENTITY_EQUIVALENCE 
END MODULE OPOV_DEMO
! ======================================================
PROGRAM OPERATOR_OVERLOADING
	USE OPOV_DEMO
	TYPE(ENTITY) :: E1, E2, E3
	
	E1%ENTITY_ID	= 12
	E1%ENTITY_VALUE = 100.25
	
	E2%ENTITY_ID	= 22
	E2%ENTITY_VALUE = 2.287
	
	E3 = E1
	CALL PRINT_ENTITY(E3)
	
	E3 = E1 + E2
	CALL PRINT_ENTITY(E3)
	
	E3 = E1 - E2
	CALL PRINT_ENTITY(E3)
	
END PROGRAM OPERATOR_OVERLOADING
