! In Fortran, a function passes a return value, but a subroutine does not.
PROGRAM FUNCTIONS_AND_SUBROUTINES
	REAL(KIND = 4) :: A
	A = 10.00
	WRITE(*,*) TEST_FUNCTION(A)	
END PROGRAM FUNCTIONS_AND_SUBROUTINES


FUNCTION TEST_FUNCTION(X)
	TEST_FUNCTION = X*X
	RETURN
END FUNCTION TEST_FUNCTION