PROGRAM INTERFACES
	INTERFACE ACCEPT_ARGUMENT
		SUBROUTINE ACCEPT_ARGUMENT_INTEGER(X)	! Accepts Integer 
			INTEGER(KIND = 4),INTENT(IN) :: X
		END SUBROUTINE ACCEPT_ARGUMENT_INTEGER

		SUBROUTINE ACCEPT_ARGUMENT_REAL(X)		! Accepts Real
			REAL(KIND = 8),INTENT(IN) :: X
		END SUBROUTINE ACCEPT_ARGUMENT_REAL
	END INTERFACE ACCEPT_ARGUMENT

	INTEGER :: I
	REAL(8) :: R

	WRITE(*,*) "EXAMPLE OF FUNCTION OVERLOADING"
	I = 109
	R = 2345.53464
	CALL ACCEPT_ARGUMENT(I)
	CALL ACCEPT_ARGUMENT(R)
	
	WRITE(*,*) "EXAMPLE OF OPERATOR OVERLOADING"

END PROGRAM INTERFACES

SUBROUTINE ACCEPT_ARGUMENT_INTEGER(X)
	INTEGER(KIND = 4) ,INTENT(IN) :: X
	WRITE(*,*) "PRINT OUT THE ARGUMENT :: ", X
END SUBROUTINE ACCEPT_ARGUMENT_INTEGER

SUBROUTINE ACCEPT_ARGUMENT_REAL(X)
	REAL(KIND = 8) ,INTENT(IN) :: X
	WRITE(*,*) "PRINT OUT THE ARGUMENT :: ", X
END SUBROUTINE ACCEPT_ARGUMENT_REAL