PROGRAM CALCULATOR
	IMPLICIT NONE
	INTEGER :: I,J
	INTEGER :: INPUT(2)
	INTEGER :: RESULTS(20)
	
	WRITE(*,*) "OPERATIONS CAPABLE"
	WRITE(*,*) "OPERATIONS PENDING"
	WRITE(*,*) "	ARITHMETIC OPERATIONS"
	WRITE(*,*) "	STATISTICAL OPERATIONS"
	WRITE(*,*) "	CALCULUS"
	WRITE(*,*) "	ALGEBRA"
	WRITE(*,*) "	GEOMETRY"
	
	
	
	WRITE(*,*) "ENTER DESIRED SHAPE OPTION::"
	WRITE(*,*) "1. EQUILATERAL TRIANGLE"
	WRITE(*,*) "2. SQUARE"
	WRITE(*,*) "3. REGULAR PENTAGON"
	WRITE(*,*) "4. REGULAR HEXAGON"
	WRITE(*,*) "5. REGULAR HEPTAGON"
	WRITE(*,*) "6. REGULAR OCTAGON"
	WRITE(*,*) "7. REGULAR NONAGON"
	WRITE(*,*) "8. REGULAR DECAGON"
	READ(*,*) INPUT(1)
	
	SELECT CASE(INPUT(1))
	
	CASE(1) 
	CASE(2) 
	CASE(3) 
	CASE(4) 
	CASE(5) 
	END SELECT
	
	
	WRITE(*,*) "ENTER 2 Numbers to perform basic operations on: "
	READ(*,*) INPUT(1),INPUT(2)
	
	WRITE(*,*) "ADDITION OF 2 NUMBERS"
	RESULTS(1)	= INPUT(1) + INPUT(2)
	WRITE(*,*) "SUBTRACTION OF 2 NUMBERS"
	RESULTS(2)	= INPUT(1) - INPUT(2)
	WRITE(*,*) "PRODUCT OF 2 NUMBERS"
	RESULTS(3)	= INPUT(1) * INPUT(2)
	WRITE(*,*) "QUOTIENT OF 2 NUMBERS"
	RESULTS(4)	= INPUT(1) / INPUT(2)
	WRITE(*,*) "REMAINDER OF 2 NUMBERS"
	RESULTS(5)	=  MOD(INPUT(1),INPUT(2))
	
	WRITE(*,*) "RESULTS ARE AS FOLLOWS: "
	WRITE(*,*) "SUM ",RESULTS(1)
	WRITE(*,*) "DIFFERENCE ",RESULTS(2)
	WRITE(*,*) "PRODUCT ",RESULTS(3)
	WRITE(*,*) "QUOTIENT ",RESULTS(4)
	WRITE(*,*) "REMAINDER ",RESULTS(5)
END PROGRAM CALCULATOR